name: Build docker on main branch every day


env:
  IMAGE_NAME: ${{ github.repository }}

on:
  schedule:
    # The actual run time usually delays for 2~3 hours
    - cron:  "36 4 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  check-today-has-commit-and-build-docker:
    runs-on: ubuntu-latest
    outputs:
      check-result: ${{ steps.check-commit.outputs.check-result }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Check today has commits
        id: check-commit
        run: |
          python -m pip install GitPython
          echo "::set-output name=check-result::$(python check_today_has_commit.py)"
      - name: Build and push Docker image
        if: ${{ steps.check-commit.outputs.check-result == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          image: zhongbazhu/nas_auto_update_clash
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
